# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd5f56f5500f6f534eb914fdca9097790e1609c91b109ffa334aebe50652c00af98b4e3733891a31e5d1711561dd0dbd74239735ec17f170ba4577326c5fa2e

test:
  secret_key_base: 6bf6b0ae2f5a8ce02352c4e3963e6a4a40db161b5bd334a86285bafe66f531a6c9bb8a5d85e3db02c38679efd341d95f8ad341728532af8ea1fda48228edb7c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
